### ISSUE TITLE
A9n.custom_file.test should read value ENV['CUSTOM_FILE_TEST']

### ISSUE THREAD

**Issue by ArturT** [knapo/a9n#10]
I'd like to use the gem like this:

```yml
# config/a9n/aws.yml
defaults:
  test: :env
```

and `A9n.aws.test` should return value for ENV['AWS_TEST']

Right now it's like that:
```
$ AWS_TEST=a TEST=b rails cosole
2.2.3 :001 > A9n.aws.test
 => "b"
2.2.3 :001 > A9n.emails.test
 => "b"
```
when ymls are:

```yml
# config/a9n/aws.yml
defaults:
  test: :env

# config/emails/aws.yml
defaults:
  test: :env
```
This is a bit confusing.
